baseurl = "https://blog.cydev.ru/"
languageCode = "ru-ru"
title = "Cydev blog"
theme = "hyde-x"

[author]
    name = "ernado"

[params]
    github = "https://github.com/cydev"
    tagline = "Automate everything."
